import type { Metadata } from "next";
import Link from "next/link";
import LiveSizes from "./LiveSizes";

export const metadata: Metadata = {
  title: "About Sakia — AI, safeguards and data",
  description: "What the AI does in Sakia, why not a spreadsheet, the safeguards, and the data card.",
};

// Contenu repris de docs/WB-VIDEO.md, docs/WB-EXIGENCES.md et docs/DATA-CARD.md. En anglais d'abord (jury).

const EVIDENCE = [
  ["Agriculture's share of water withdrawals", "75.5 % (2.71 of 3.59 km³)", "FAO AQUASTAT, Tunisia", "2022", "Some values imputed"],
  ["Kairouan aquifer exploited at", "230 %", "African Manager (press)", "2024", "Press, not an official report"],
  ["Households with internet, Kairouan", "20.7 % (national 40.4 %)", "INS, ICT bulletin", "2025", "Households, not individuals"],
  ["Illiteracy, Kairouan (age 10+)", "25.5 to 28.5 % (national 17.3 %)", "INS, census", "2024", "Range read from a summary"],
  ["SMS received at the right time in a pilot", "15 % of 421 respondents", "ICARDA, ICT2Scale (WOCAT)", "2019-2021", "Small pilot"],
  ["Pumping cost for farms under 3 ha", "1.25 to 1.5 times higher", "Cahiers Agricultures", "2024", "Read via a summary: to verify"],
];

const DATASETS = [
  [
    "Weather forecast (FAO ET0, rain, temperature)",
    "7-day plan",
    "Open-Meteo (ECMWF, ICON, GFS models)",
    "CC BY 4.0; free for non-commercial use",
    "Measured live below",
    "9 to 25 km grid, no local station; grid ET0 can underestimate need (a Morocco study: -2 to -37 %); weak reliability beyond 7 days",
  ],
  [
    "ERA5 weather archive",
    "Backtest, 11 seasons",
    "Open-Meteo (ERA5)",
    "CC BY 4.0",
    "4,291 days for Kairouan",
    "Same limits; point of the governorate capital, not the plot",
  ],
  [
    "Crop coefficients (Kc, p, Zr, Ky)",
    "Water need",
    "FAO Irrigation and Drainage Paper 56 (tables 11, 12, 22, 24); Pereira et al. 2024 (trees)",
    "FAO / Springer publications (values cited, not redistributed in bulk)",
    "18 crops",
    "Generic values, no Tunisian field trials; Ky missing for barley, melon and all trees; pomegranate and fig by analogy",
  ],
  [
    "Tunisia crop calendar",
    "Planting dates",
    "FAO CropCalendar",
    "FAO",
    "15 annual crops",
    "Missing for olive, almond, vine, citrus, date palm, alfalfa; no Kairouan-specific calendar except chili, olive, cereals",
  ],
  [
    "Soil available water",
    "Water reserve",
    "FAO-56 table 19 (indicative: 90, 150, 170 mm/m)",
    "FAO",
    "3 soil classes",
    "No real soil map (SoilGrids possible, not integrated)",
  ],
  [
    "Synthetic voice",
    "Spoken bulletin",
    "ElevenLabs (voice “Rima M”, Tunisian accent)",
    "ElevenLabs terms (Creator plan)",
    "About 4 KB per second of audio",
    "Reads Darija text with a Tunisian-accent voice; not validated by a native speaker",
  ],
  [
    "Speech recognition",
    "Farmer's spoken question",
    "ElevenLabs Scribe",
    "ElevenLabs terms",
    "n/a",
    "Provider reports French excellent, Arabic average, Tunisian dialect not evaluated; to be measured on our phrases",
  ],
  [
    "Training data of the small intent model",
    "Understanding “zitoun kairouan”",
    "SYNTHETIC: generated by us (phrase templates in French, Arabic, Arabizi)",
    "Produced for this project",
    "To be measured",
    "Labelled synthetic; no real farmer messages; covers 18 crops and 24 governorates",
  ],
];

const NOT_COVERED = [
  "No field trial in Tunisia: coefficients are generic, so the advice is indicative.",
  "No local weather station and no soil-moisture sensor.",
  "No farmer registry, no market prices, no water salinity.",
  "The “fixed calendar” of the backtest is an assumption: the administration's real calendar was not obtained.",
  "Relative yield is estimated only for the 9 crops with a published Ky, never for trees.",
  "Darija text and speech are not yet validated by a native speaker; recognition of Darija is not guaranteed and is still being measured.",
  "No personal data beyond a conversation identifier, a language, a region, a crop and a few settings.",
];

const REASONS = [
  ["The weather data is more than 48 hours old", "No advice is given at all"],
  ["The weather data is more than 12 hours old", "Advice shown, flagged “not sure”"],
  ["The last irrigation is not known", "Flagged “not sure”"],
  ["This crop's coefficients are estimated by analogy", "Flagged “not sure”"],
  ["Rain is possible within 3 days (30 to 70 % probability)", "Flagged “not sure”"],
  ["The forecast does not cover the whole week", "Flagged “not sure”"],
];

function Section({ id, title, children }: { id: string; title: string; children: React.ReactNode }) {
  return (
    <section aria-labelledby={id} className="space-y-3">
      <h2 id={id} className="text-xl font-extrabold text-sakia-green">
        {title}
      </h2>
      {children}
    </section>
  );
}

function Table({ head, rows }: { head: string[]; rows: string[][] }) {
  return (
    <div className="overflow-x-auto rounded-xl border border-sakia-sand-dark bg-white">
      <table className="w-full min-w-[40rem] border-collapse text-start text-sm">
        <thead className="bg-sakia-sand text-sakia-brown">
          <tr>
            {head.map((h) => (
              <th key={h} scope="col" className="px-3 py-2 text-start font-bold">
                {h}
              </th>
            ))}
          </tr>
        </thead>
        <tbody>
          {rows.map((r, i) => (
            <tr key={i} className="border-t border-sakia-sand-dark align-top">
              {r.map((c, j) => (
                <td key={j} className={`px-3 py-2 ${j === 0 ? "font-semibold text-sakia-ink" : "text-sakia-ink"}`}>
                  {c}
                </td>
              ))}
            </tr>
          ))}
        </tbody>
      </table>
    </div>
  );
}

export default function AboutPage() {
  return (
    <main dir="ltr" lang="en" className="mx-auto w-full max-w-3xl flex-1 space-y-8 px-4 py-6 text-start">
      <p className="rounded-xl bg-sakia-sand p-3 text-sm text-sakia-brown">
        This page is in English. Sakia speaks to farmers in Tunisian Arabic (Darija), standard Arabic, French and English.
      </p>

      <Section id="problem" title="The problem, in one sentence">
        <p className="rounded-xl bg-sakia-green p-4 text-lg font-semibold leading-relaxed text-white">
          Because of Sakia, a smallholder in Kairouan will irrigate on the day the crop needs it, before heat stress,
          instead of following a fixed calendar that wastes water or arrives late; we know because, over 11 replayed
          seasons of real weather, the advised schedule used 3 to 27 % less pumped water with almost no stress days
          (a simulation, not a field measurement), and in a past SMS pilot only 15 % of farmers received messages at the
          right time.
        </p>
        <p className="text-sm text-sakia-brown">
          The simulation is on the{" "}
          <Link href="/backtest" className="font-semibold underline">
            proof page
          </Link>
          , with its assumptions.
        </p>
      </Section>

      <Section id="ai" title="What does the AI do, and why not a spreadsheet?">
        <p className="leading-relaxed text-sakia-ink">
          The numbers come from a deterministic FAO-56 water balance, <strong>on purpose</strong>: it can be checked, and
          it cannot hallucinate. A spreadsheet could do that calculation.
        </p>
        <p className="leading-relaxed text-sakia-ink">
          What a spreadsheet cannot do is meet the farmer where the language is the barrier. About one adult in four in
          Kairouan cannot read, and many speak only Tunisian Arabic (Darija), which is spoken far more than it is
          written. So the AI is used to understand a farmer who speaks or writes in Darija, French or Latin-script
          Tunisian (“Arabizi”), to fill in the crop and region on their behalf, and to answer aloud in Darija.
        </p>
        <p className="rounded-xl border border-sakia-sand-dark bg-sakia-sand p-3 text-sm text-sakia-brown">
          <strong>Status, stated plainly:</strong> speech recognition and intent understanding have not yet been measured
          on real phrases. We will publish the result as it comes, even if it is poor.
        </p>
      </Section>

      <Section id="languages" title="Languages">
        <ul className="list-disc space-y-1 ps-5 text-sakia-ink">
          <li>
            <strong>Tunisian Arabic (Darija) comes first.</strong> The spoken bulletin and the on-screen text can be in
            Darija, written in Arabic letters, because it is the language of farmers who do not read standard Arabic
            comfortably.
          </li>
          <li>Standard Arabic, French and English are also available everywhere.</li>
          <li>Typed input also accepts Latin-script Tunisian (“zitoun kairouan”) in the SMS simulator.</li>
          <li>
            <strong>Our answer to “what about a less-supported language?”</strong> Darija is exactly that case. It has no
            standard spelling, and the speech-recognition provider has not evaluated it. Our Darija text is built from
            fixed templates in common Tunisian words, with an automated check that rejects Moroccan and Egyptian forms.
            It has <strong>not yet been checked by a native speaker</strong>, and we will publish recognition results as
            measured, even if they are poor.
          </li>
        </ul>
      </Section>

      <Section id="safeguards" title="Safeguards">
        <ul className="list-disc space-y-1 ps-5 text-sakia-ink">
          <li>
            <strong>A human decides.</strong> The advice is indicative and must be validated by the regional agricultural
            administration (CRDA).
          </li>
          <li>
            <strong>“Not sure: ask a person.”</strong> When the tool cannot give a reliable answer it says so, in fixed
            sentences that are never generated freely, and it does not guess.
          </li>
          <li>The calculation is deterministic and the assumptions are always visible.</li>
          <li>Estimates are never presented as measurements; estimated days are labelled.</li>
          <li>No personal data is collected beyond a conversation identifier and a few settings.</li>
        </ul>
        <Table head={["When the tool says “not sure”", "What the user sees"]} rows={REASONS} />
      </Section>

      <Section id="size" title="Small AI: measured sizes">
        <p className="text-sm text-sakia-brown">
          No large model runs on the device. These sizes are measured live from this site (bytes received, before compression).
        </p>
        <div className="rounded-xl bg-white p-4">
          <LiveSizes />
        </div>
      </Section>

      <Section id="data" title="Data card">
        <h3 className="text-base font-bold text-sakia-brown">A. Evidence that shows the problem</h3>
        <Table head={["Fact", "Value", "Source", "Year", "Caveat"]} rows={EVIDENCE} />
        <h3 className="pt-2 text-base font-bold text-sakia-brown">B. Data the tool works with</h3>
        <Table
          head={["Dataset", "Role", "Source", "Licence", "Size", "What it does not cover"]}
          rows={DATASETS}
        />
        <h3 className="pt-2 text-base font-bold text-sakia-brown">C. What our data does not cover</h3>
        <ul className="list-disc space-y-1 ps-5 text-sakia-ink">
          {NOT_COVERED.map((n) => (
            <li key={n}>{n}</li>
          ))}
        </ul>
      </Section>

      <Section id="limits" title="Limits">
        <ul className="list-disc space-y-1 ps-5 text-sakia-ink">
          <li>SMS and voice channels are simulated; the same engine would serve real ones.</li>
          <li>“Offline” means without internet, not without a mobile network. Telegram needs a connection.</li>
          <li>Crop coefficients are generic and not validated by farmers: the advice is indicative.</li>
          <li>The impact figures are model estimates on real historical weather, not measured in the field.</li>
          <li>The weather point is the governorate capital, an approximation of the plot.</li>
        </ul>
      </Section>
    </main>
  );
}
