// Libellés de la page /call (faux téléphone) en français, arabe et anglais. Aucun chiffre du moteur ici :
// les valeurs viennent du plan ou du catalogue. Les phrases DITES au téléphone sont dans src/lib/ivr/prompts.ts.
// L'ARABE EST À FAIRE VALIDER par un locuteur tunisien.

export type UiLang = "fr" | "ar" | "en";
// Le sélecteur de langue du site propose aussi la darija (aeb) : la page /call l'affiche en arabe standard.
export const uiLangOf = (l: string): UiLang => (l === "fr" || l === "en" ? l : "ar");

type Dict = Record<string, string>;

const fr: Dict = {
  title: "Ligne vocale : appeler Sakia",
  backHome: "Retour à l'accueil",
  langOrderTitle: "Langues",
  langOrder:
    "Arabe (touche 2) ou français (touche 1), sous-titres en anglais. La voix arabe parle un arabe standard simple à accent tunisien ; son texte n'est pas validé par un locuteur tunisien.",
  intro: "Appelez, écoutez, tapez une touche. Un téléphone basique suffit.",
  stat:
    "À Kairouan, 27,9 % des personnes de 10 ans et plus ne savent pas lire (recensement INS 2024, chiffre relayé par la presse) : un SMS ne les atteint pas.",
  simulated: "SIMULATION : ce téléphone est dessiné. Aucun numéro réel, aucun vrai appel, aucun enregistrement de vos appels.",
  callBtn: "Appeler Sakia",
  keypad: "Touches du téléphone",
  hangBtn: "Raccrocher",
  callAgain: "Rappeler",
  idleHint: "Appuyez sur « Appeler Sakia », puis sur les touches du téléphone (ou de votre clavier).",
  ringing: "Ça sonne…",
  active: "Appel en cours",
  ended: "Appel terminé",
  duration: "Durée",
  maxCall: "La ligne se termine d'elle-même après 2 minutes.",
  speaking: "Sakia parle",
  listening: "À vous : tapez une touche",
  loadingPlan: "Calcul du conseil…",
  keysNow: "Touches",
  alwaysKeys: "0 : répéter · * : revenir en arrière",
  transcript: "Transcription de l'appel (elle reste dans cette page, rien n'est enregistré)",
  youPressed: "Vous : touche {k}",
  noHang: "Appel raccroché.",
  sourceTitle: "D'où vient la voix du conseil ?",
  sourceAuto: "Automatique : voix en direct avec la météo du jour ; sans internet, enregistrement de démonstration",
  sourceRec: "Enregistrements seulement (simule l'absence d'internet)",
  online: "Internet : oui",
  offline: "Internet : non",
  bannerLive: "Voix en direct · météo du {date}",
  bannerCache: "Voix déjà synthétisée pour ce texte (mémoire du serveur) · météo du {date}",
  bannerRec: "ENREGISTREMENT de démonstration : rejeu du {date} (météo observée ce jour-là), pas la météo d'aujourd'hui.",
  bannerNoVoiceBudget: "La voix en direct est suspendue (budget de la démonstration atteint) : le conseil est affiché à l'écran seulement.",
  bannerNoVoice: "La voix n'est pas disponible pour le moment : le conseil est affiché à l'écran seulement.",
  bannerNoRec: "Pas d'enregistrement pour ce choix sans internet. Choix enregistrés : {list}. L'appel dit donc « pas sûr : demandez à un technicien ».",
  bannerError: "Le conseil n'a pas pu être calculé. L'appel dit « pas sûr : demandez à un technicien ».",
  bannerRecChoices: "Hors connexion, les enregistrements couvrent : {list}.",
  recList2: "touche 2 (arrosé hier ou avant-hier) : {crops}",
  recList9: "touche 9 (je ne sais pas) : {crops}",
  guardTitle: "Garde-fou",
  guardNone: "Aucun conseil donné : les données météo sont trop anciennes. Demandez à un technicien agricole (CRDA).",
  guardAsk: "Je ne suis pas sûr : demandez à un technicien agricole (CRDA).",
  guardOk: "Aucune réserve du moteur sur ce conseil (données récentes, dernier arrosage connu).",
  guardWaiting: "Quand le moteur n'est pas sûr, l'appel le dit à voix haute.",
  guardWhy: "Pourquoi :",
  reason_very_stale_data: "les données météo ont plus de 48 heures",
  reason_stale_data: "les données météo ont plus de 12 heures",
  reason_unknown_last_irrigation: "le dernier arrosage n'est pas connu",
  reason_analogy_coefficients: "les coefficients de cette culture sont estimés par analogie",
  reason_uncertain_rain: "de la pluie est possible dans les 3 jours",
  reason_short_horizon: "la prévision ne couvre pas toute la semaine",
  prepTitle: "Écouter sans internet",
  prepText:
    "Garde les {n} enregistrements ({size}) dans ce navigateur : ensuite la ligne marche sans internet (non vérifié en mode avion sur un téléphone).",
  prepBtn: "Préparer le hors-ligne",
  prepRunning: "Téléchargement : {done} / {total}",
  prepDone: "Prêt : {n} fichiers gardés dans ce navigateur.",
  prepPartial: "{n} fichiers gardés sur {total}. Réessayez avec internet.",
  plugTitle: "Comment ça se brancherait",
  plug1: "Un numéro court auprès d'un opérateur tunisien, ou une ligne SIP chez un fournisseur de téléphonie. Aucun numéro n'existe.",
  plug2: "Chaque touche reçue est envoyée à POST /api/ivr/step : c'est la même machine à états que ce faux téléphone. La réponse donne les fichiers audio à jouer.",
  plug3: "Le conseil lu vient de GET /api/ivr/plan-audio : même moteur d'irrigation, même garde-fou « pas sûr ».",
  plug4: "Un appel vocal ordinaire suffit : pas d'internet chez l'agriculteur, pas d'application, pas de lecture.",
  plug5: "Accord avec un opérateur, coût des minutes, vérification de l'appelant, consentement et règle de non-enregistrement.",
  realTitle: "Ce qui est réel, ce qui est simulé",
  real1: "Réel : le moteur d'irrigation (météo Open-Meteo), la voix de synthèse (ElevenLabs, voix Rima M), l'arbre de dialogue.",
  real2: "Simulé : le téléphone et le réseau téléphonique.",
  real3: "Arabe : arabe standard simple lu avec un accent tunisien, pas de dialecte garanti. Textes à valider par un Tunisien.",
  real4: "Le conseil est indicatif : une personne décide. À valider auprès de l'administration agricole régionale.",
  sizes: "Phrases fixes : {n} fichiers ({kb} Ko, trois langues). Une lecture de plan pèse environ {planKb} Ko.",
  talkLink: "Ou parlez simplement à Sakia",
  hint_lang_fr: "Français",
  hint_lang_ar: "العربية (arabe)",
  hint_lang_en: "Anglais (English)",
  simBadge: "Simulé",
  hint_region_other: "Une autre région",
  hint_again_yes: "Écouter une autre culture",
  hint_again_no: "Terminer l'appel",
  hint_again_detail: "Détail de la semaine",
  hint_skip: "Toute touche : passer à la suite",
  group_cereales: "Céréales",
  group_legumes: "Légumes",
  group_arbres: "Arbres",
  group_autres: "Autres cultures",
  ago_1: "Aujourd'hui",
  ago_2: "Hier ou avant-hier",
  ago_3: "Il y a 3 à 5 jours",
  ago_4: "Il y a plus de 5 jours",
  ago_9: "Je ne sais pas (le plan sera « pas sûr »)",
  voiceFootnote: "Voix : {voice} (ElevenLabs), sous-titres anglais pour le jury.",
};

const en: Dict = {
  title: "Voice line: call Sakia",
  backHome: "Back to home",
  langOrderTitle: "Languages",
  langOrder:
    "Arabic (key 2) or French (key 1), with English subtitles. The Arabic voice is simple standard Arabic with a Tunisian accent; its text is not validated by a Tunisian speaker.",
  intro: "Call, listen, press a key. A basic phone is enough.",
  stat:
    "In Kairouan, 27.9% of people aged 10 and over cannot read (INS 2024 census, figure relayed by the press): a text message does not reach them.",
  simulated: "SIMULATION: this phone is drawn. No real number, no real call, and your calls are not recorded.",
  callBtn: "Call Sakia",
  keypad: "Phone keys",
  hangBtn: "Hang up",
  callAgain: "Call again",
  idleHint: "Press “Call Sakia”, then use the keypad (or your keyboard).",
  ringing: "Ringing…",
  active: "Call in progress",
  ended: "Call ended",
  duration: "Duration",
  maxCall: "The line ends by itself after 2 minutes.",
  speaking: "Sakia is speaking",
  listening: "Your turn: press a key",
  loadingPlan: "Working out the advice…",
  keysNow: "Keys",
  alwaysKeys: "0: repeat · *: go back",
  transcript: "Call transcript (it stays in this page, nothing is recorded)",
  youPressed: "You: key {k}",
  noHang: "Call hung up.",
  sourceTitle: "Where does the voice of the advice come from?",
  sourceAuto: "Automatic: live voice with today's weather; without internet, a demo recording",
  sourceRec: "Recordings only (simulates having no internet)",
  online: "Internet: yes",
  offline: "Internet: no",
  bannerLive: "Live voice · weather of {date}",
  bannerCache: "Voice already synthesised for this text (server memory) · weather of {date}",
  bannerRec: "DEMO RECORDING: replay of {date} (weather observed that day), not today's weather.",
  bannerNoVoiceBudget: "The live voice is paused (the demo budget is used up): the advice is shown on screen only.",
  bannerNoVoice: "The voice is not available right now: the advice is shown on screen only.",
  bannerNoRec: "No recording for this choice without internet. Recorded choices: {list}. The call therefore says “not sure: ask a technician”.",
  bannerError: "The advice could not be worked out. The call says “not sure: ask a technician”.",
  bannerRecChoices: "Offline, the recordings cover: {list}.",
  recList2: "key 2 (watered yesterday or the day before): {crops}",
  recList9: "key 9 (I do not know): {crops}",
  guardTitle: "Safeguard",
  guardNone: "No advice given: the weather data is too old. Ask an agricultural technician (CRDA).",
  guardAsk: "I am not sure: please ask an agricultural technician (CRDA).",
  guardOk: "The engine has no reservation about this advice (recent data, last irrigation known).",
  guardWaiting: "When the engine is not sure, the call says so out loud.",
  guardWhy: "Why:",
  reason_very_stale_data: "the weather data is more than 48 hours old",
  reason_stale_data: "the weather data is more than 12 hours old",
  reason_unknown_last_irrigation: "the last irrigation is not known",
  reason_analogy_coefficients: "this crop's coefficients are estimated by analogy",
  reason_uncertain_rain: "rain is possible within 3 days",
  reason_short_horizon: "the forecast does not cover the whole week",
  prepTitle: "Listen without internet",
  prepText:
    "Keeps the {n} recordings ({size}) in this browser: then the line works without internet (not checked in a phone's airplane mode).",
  prepBtn: "Get ready for offline",
  prepRunning: "Downloading: {done} / {total}",
  prepDone: "Ready: {n} files kept in this browser.",
  prepPartial: "{n} of {total} files kept. Try again with internet.",
  plugTitle: "How it would plug in",
  plug1: "A short number from a Tunisian operator, or a SIP line from a telephony provider. No number exists.",
  plug2: "Each key received is sent to POST /api/ivr/step: the same state machine as this fake phone. The answer lists the audio files to play.",
  plug3: "The advice read aloud comes from GET /api/ivr/plan-audio: same irrigation engine, same “not sure” safeguard.",
  plug4: "An ordinary voice call is enough: no internet for the farmer, no app, no reading.",
  plug5: "An agreement with an operator, the cost of minutes, caller verification, consent and a no-recording rule.",
  realTitle: "What is real, what is simulated",
  real1: "Real: the irrigation engine (Open-Meteo weather), the synthetic voice (ElevenLabs, Rima M voice), the dialogue tree.",
  real2: "Simulated: the phone and the telephone network.",
  real3: "Arabic: simple Modern Standard Arabic read with a Tunisian accent, no dialect guaranteed. Texts to be validated by a Tunisian speaker.",
  real4: "The advice is indicative: a person decides. To be checked with the regional agriculture office.",
  sizes: "Fixed sentences: {n} files ({kb} KB, three languages). One plan reading weighs about {planKb} KB.",
  talkLink: "Or just talk to Sakia",
  hint_lang_fr: "French",
  hint_lang_ar: "Arabic (العربية)",
  hint_lang_en: "English",
  simBadge: "Simulated",
  hint_region_other: "Another region",
  hint_again_yes: "Hear another crop",
  hint_again_no: "End the call",
  hint_again_detail: "Week details",
  hint_skip: "Any key: skip to the next step",
  group_cereales: "Cereals",
  group_legumes: "Vegetables",
  group_arbres: "Trees",
  group_autres: "Other crops",
  ago_1: "Today",
  ago_2: "Yesterday or the day before",
  ago_3: "3 to 5 days ago",
  ago_4: "More than 5 days ago",
  ago_9: "I do not know (the plan will say “not sure”)",
  voiceFootnote: "Voice: {voice} (ElevenLabs), English subtitles for the jury.",
};

const ar: Dict = {
  title: "الخط الصوتي: اتصلوا بساقية",
  backHome: "العودة إلى الصفحة الرئيسية",
  langOrderTitle: "اللغات",
  langOrder:
    "يتكلم الخط بالفرنسية (الزر 1) وبالعربية (الزر 2). الترجمة بالإنجليزية. الصوت العربي عربية فصحى بسيطة بلكنة تونسية، وليس باللهجة التونسية؛ ونصّه لم يراجعه متحدث تونسي.",
  intro: "اتصلوا، استمعوا، واختاروا بأزرار الهاتف. يكفي هاتف بسيط.",
  stat:
    "في القيروان، 27,9 % من الأشخاص البالغين 10 سنوات فأكثر لا يقرؤون (المعهد الوطني للإحصاء، تعداد 2024، رقم نقلته الصحافة)، والرسالة النصية لا تنفع من لا يقرأ.",
  simulated: "محاكاة: هذا الهاتف مرسوم. لا رقم حقيقي ولا مكالمة حقيقية ولا تسجيل لمكالماتكم.",
  callBtn: "اتصل بساقية",
  keypad: "أزرار الهاتف",
  hangBtn: "إنهاء المكالمة",
  callAgain: "اتصل من جديد",
  idleHint: "اضغطوا على «اتصل بساقية» ثم على أزرار الهاتف (أو لوحة المفاتيح).",
  ringing: "يرنّ الهاتف…",
  active: "المكالمة جارية",
  ended: "انتهت المكالمة",
  duration: "المدة",
  maxCall: "ينتهي الخط تلقائيا بعد دقيقتين.",
  speaking: "ساقية تتكلم",
  listening: "دوركم: اضغطوا زرا",
  loadingPlan: "جارٍ حساب النصيحة…",
  keysNow: "الأزرار",
  alwaysKeys: "0: للإعادة · *: للرجوع",
  transcript: "نص المكالمة (يبقى في هذه الصفحة، ولا يُسجَّل شيء)",
  youPressed: "أنتم: الزر {k}",
  noHang: "تم إنهاء المكالمة.",
  sourceTitle: "من أين يأتي صوت النصيحة؟",
  sourceAuto: "تلقائي: صوت مباشر بطقس اليوم؛ وبدون إنترنت، تسجيل تجريبي",
  sourceRec: "التسجيلات فقط (لمحاكاة غياب الإنترنت)",
  online: "الإنترنت: نعم",
  offline: "الإنترنت: لا",
  bannerLive: "صوت مباشر · طقس {date}",
  bannerCache: "صوت سبق توليده لهذا النص (ذاكرة الخادم) · طقس {date}",
  bannerRec: "تسجيل تجريبي: إعادة ليوم {date} (طقس مرصود في ذلك اليوم)، وليس طقس اليوم.",
  bannerNoVoiceBudget: "الصوت المباشر متوقف (نفدت ميزانية العرض): النصيحة معروضة على الشاشة فقط.",
  bannerNoVoice: "الصوت غير متوفر حاليا: النصيحة معروضة على الشاشة فقط.",
  bannerNoRec: "لا يوجد تسجيل لهذا الاختيار بدون إنترنت. الاختيارات المسجلة: {list}. لذلك تقول المكالمة «لست متأكدا: اسألوا فنيا».",
  bannerError: "تعذر حساب النصيحة. تقول المكالمة «لست متأكدا: اسألوا فنيا».",
  bannerRecChoices: "بدون إنترنت، تغطي التسجيلات: {list}.",
  recList2: "الزر 2 (سقيتم أمس أو أول أمس): {crops}",
  recList9: "الزر 9 (لا أعرف): {crops}",
  guardTitle: "صمام الأمان",
  guardNone: "لا نصيحة: بيانات الطقس قديمة جدا. اسألوا فنيا فلاحيا (CRDA).",
  guardAsk: "لست متأكدا: اسألوا فنيا فلاحيا (المندوبية الجهوية للتنمية الفلاحية).",
  guardOk: "لا تحفظ لدى المحرك على هذه النصيحة (بيانات حديثة، وآخر سقي معروف).",
  guardWaiting: "حين لا يكون المحرك متأكدا، تقول المكالمة ذلك بصوت مسموع.",
  guardWhy: "السبب:",
  reason_very_stale_data: "بيانات الطقس أقدم من 48 ساعة",
  reason_stale_data: "بيانات الطقس أقدم من 12 ساعة",
  reason_unknown_last_irrigation: "تاريخ آخر سقي غير معروف",
  reason_analogy_coefficients: "معاملات هذا المحصول مقدرة بالمقارنة",
  reason_uncertain_rain: "قد تسقط أمطار خلال 3 أيام",
  reason_short_horizon: "التوقعات لا تغطي الأسبوع كله",
  prepTitle: "الاستماع بدون إنترنت",
  prepText:
    "يحفظ في هذا المتصفح {n} تسجيلا ({size}): بعدها يعمل الخط بدون إنترنت (لم يُتحقق منه في وضع الطيران على هاتف).",
  prepBtn: "التحضير للعمل بدون إنترنت",
  prepRunning: "جارٍ التحميل: {done} / {total}",
  prepDone: "جاهز: {n} ملفا محفوظا في هذا المتصفح.",
  prepPartial: "حُفظ {n} ملفا من {total}. أعيدوا المحاولة مع الإنترنت.",
  plugTitle: "كيف سيُربط بالهاتف",
  plug1: "رقم قصير لدى مشغّل تونسي، أو خط SIP لدى مزوّد اتصالات. لا يوجد أي رقم.",
  plug2: "كل زر يُستقبل يُرسل إلى POST /api/ivr/step: هي نفس آلة الحالات لهذا الهاتف المرسوم. والجواب يعطي ملفات الصوت التي يجب تشغيلها.",
  plug3: "النصيحة المقروءة تأتي من GET /api/ivr/plan-audio: نفس محرك السقي، ونفس صمام «لست متأكدا».",
  plug4: "تكفي مكالمة صوتية عادية: لا إنترنت عند الفلاح ولا تطبيق ولا قراءة.",
  plug5: "اتفاق مع مشغّل، كلفة الدقائق، التحقق من المتصل، الموافقة، وقاعدة عدم التسجيل.",
  realTitle: "ما هو حقيقي وما هو محاكى",
  real1: "حقيقي: محرك السقي (طقس Open-Meteo)، الصوت الاصطناعي (ElevenLabs، صوت Rima M)، شجرة الحوار.",
  real2: "محاكى: الهاتف وشبكة الهاتف.",
  real3: "العربية: فصحى بسيطة بلكنة تونسية، دون ضمان لهجة. النصوص تحتاج إلى مراجعة من متحدث تونسي.",
  real4: "النصيحة إرشادية: القرار لشخص. يجب التحقق منها لدى المصالح الفلاحية الجهوية.",
  sizes: "الجمل الثابتة: {n} ملفا ({kb} ك.ب، ثلاث لغات). قراءة خطة واحدة تزن حوالي {planKb} ك.ب.",
  talkLink: "أو تحدّثوا مع ساقية مباشرة",
  hint_lang_fr: "الفرنسية (Français)",
  hint_lang_ar: "العربية",
  hint_lang_en: "الإنجليزية (English)",
  simBadge: "محاكاة",
  hint_region_other: "ولاية أخرى",
  hint_again_yes: "الاستماع إلى محصول آخر",
  hint_again_no: "إنهاء المكالمة",
  hint_again_detail: "تفاصيل الأسبوع",
  hint_skip: "أي زر: للانتقال إلى التالي",
  group_cereales: "الحبوب",
  group_legumes: "الخضروات",
  group_arbres: "الأشجار",
  group_autres: "محاصيل أخرى",
  ago_1: "اليوم",
  ago_2: "أمس أو أول أمس",
  ago_3: "قبل 3 إلى 5 أيام",
  ago_4: "قبل أكثر من 5 أيام",
  ago_9: "لا أعرف (ستكون الخطة «غير متأكد»)",
  voiceFootnote: "الصوت: {voice} (ElevenLabs)، ترجمة إنجليزية للجنة التحكيم.",
};

const DICTS: Record<UiLang, Dict> = { fr, en, ar };

export function tr(lang: UiLang, key: string, vars?: Record<string, string | number>): string {
  const raw = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  return vars ? raw.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`)) : raw;
}

export const LOCALES: Record<UiLang, string> = { fr: "fr-FR", en: "en-GB", ar: "ar-TN-u-nu-latn" };
