// Libellés de la page /call (faux téléphone) en français, arabe et anglais. Aucun chiffre du moteur ici :
// les valeurs viennent du plan ou du catalogue. Les phrases DITES au téléphone sont dans src/lib/ivr/prompts.ts.
// L'ARABE EST À FAIRE VALIDER par un locuteur tunisien.

export type UiLang = "fr" | "ar" | "en";
// Le sélecteur de langue du site propose aussi la darija (aeb) : la page /call l'affiche en arabe standard.
export const uiLangOf = (l: string): UiLang => (l === "fr" || l === "en" ? l : "ar");

type Dict = Record<string, string>;

const fr: Dict = {
  title: "Ligne vocale : appeler Sakia",
  langOrderTitle: "Pourquoi l'anglais d'abord ?",
  langOrder:
    "Les sous-titres sont en anglais en premier, pour le jury international. En réalité, le produit parle d'abord la darija tunisienne, puis le français, puis éventuellement l'anglais : l'anglais est très peu parlé ici. Aujourd'hui la touche 2 lit de l'arabe standard simple avec un accent tunisien ; la darija n'est pas encore enregistrée ni validée par un Tunisien.",
  intro:
    "Pour l'agriculteur qui ne lit pas : il appelle, écoute le conseil dans une voix à accent tunisien et choisit avec les touches. Un téléphone basique et du réseau vocal suffisent : pas d'internet, pas d'application, pas de lecture.",
  stat:
    "À Kairouan, 25,5 à 28,5 % des adultes ne savent pas lire (INS 2024), et un SMS ne sert à rien à qui ne lit pas. Dans le projet pilote ICT2Scale (ICARDA/GIZ), seulement 15 % des agriculteurs recevaient les SMS au bon moment : ils demandaient des appels vocaux.",
  simulated: "SIMULATION : ce téléphone est dessiné. Aucun numéro réel, aucun vrai appel, aucun enregistrement de vos appels.",
  callBtn: "Appeler Sakia",
  hangBtn: "Raccrocher",
  callAgain: "Rappeler",
  idleHint: "Appuyez sur « Appeler Sakia », puis sur les touches du téléphone (ou de votre clavier).",
  ringing: "Ça sonne…",
  active: "Appel en cours",
  ended: "Appel terminé",
  duration: "Durée",
  maxCall: "La ligne se termine d'elle-même après 2 minutes.",
  speaking: "Sakia parle",
  listening: "À vous : tapez une touche",
  loadingPlan: "Calcul du conseil…",
  keysNow: "Touches possibles maintenant (aide de la simulation)",
  alwaysKeys: "0 : répéter · * : revenir en arrière",
  transcript: "Transcription de l'appel (elle reste dans cette page, rien n'est enregistré)",
  youPressed: "Vous : touche {k}",
  noHang: "Appel raccroché.",
  sourceTitle: "D'où vient la voix du conseil ?",
  sourceAuto: "Automatique : voix en direct avec la météo du jour ; sans internet, enregistrement de démonstration",
  sourceRec: "Enregistrements seulement (simule l'absence d'internet)",
  online: "Internet : oui",
  offline: "Internet : non",
  bannerLive: "Voix en direct · météo du {date}",
  bannerCache: "Voix déjà synthétisée pour ce texte (mémoire du serveur) · météo du {date}",
  bannerRec: "ENREGISTREMENT de démonstration : rejeu du {date} (météo observée ce jour-là), pas la météo d'aujourd'hui.",
  bannerNoVoiceBudget: "La voix en direct est suspendue (budget de la démonstration atteint) : le conseil est affiché à l'écran seulement.",
  bannerNoVoice: "La voix n'est pas disponible pour le moment : le conseil est affiché à l'écran seulement.",
  bannerNoRec: "Pas d'enregistrement pour ce choix sans internet. Choix enregistrés : {list}. L'appel dit donc « pas sûr : demandez à un technicien ».",
  bannerError: "Le conseil n'a pas pu être calculé. L'appel dit « pas sûr : demandez à un technicien ».",
  bannerRecChoices: "Hors connexion, les enregistrements couvrent : {list}.",
  recList2: "touche 2 (arrosé hier ou avant-hier) : {crops}",
  recList9: "touche 9 (je ne sais pas) : {crops}",
  guardTitle: "Garde-fou",
  guardNone: "Aucun conseil donné : les données météo sont trop anciennes. Demandez à un technicien agricole (CRDA).",
  guardAsk: "Je ne suis pas sûr : demandez à un technicien agricole (CRDA).",
  guardOk: "Aucune réserve du moteur sur ce conseil (données récentes, dernier arrosage connu).",
  guardWaiting: "S'affichera après la lecture d'un conseil. Quand le moteur n'est pas sûr, l'appel le dit à voix haute.",
  guardWhy: "Pourquoi :",
  reason_very_stale_data: "les données météo ont plus de 48 heures",
  reason_stale_data: "les données météo ont plus de 12 heures",
  reason_unknown_last_irrigation: "le dernier arrosage n'est pas connu",
  reason_analogy_coefficients: "les coefficients de cette culture sont estimés par analogie",
  reason_uncertain_rain: "de la pluie est possible dans les 3 jours",
  reason_short_horizon: "la prévision ne couvre pas toute la semaine",
  prepTitle: "Écouter sans internet",
  prepText:
    "Garde dans ce navigateur les {n} enregistrements ({size}) : les phrases du menu et les plans de démonstration. Ensuite la ligne marche en mode avion. La page elle-même doit avoir été ouverte une fois avec internet.",
  prepBtn: "Préparer le hors-ligne",
  prepRunning: "Téléchargement : {done} / {total}",
  prepDone: "Prêt : {n} fichiers gardés dans ce navigateur.",
  prepPartial: "{n} fichiers gardés sur {total}. Réessayez avec internet.",
  plugTitle: "Comment ça se brancherait (non construit)",
  plug1: "Un numéro court auprès d'un opérateur tunisien, ou une ligne SIP chez un fournisseur de téléphonie. Aucun numéro n'existe aujourd'hui.",
  plug2: "Chaque touche reçue est envoyée à POST /api/ivr/step : c'est la même machine à états que ce faux téléphone. La réponse donne les fichiers audio à jouer.",
  plug3: "Le conseil lu vient de GET /api/ivr/plan-audio : même moteur d'irrigation, même garde-fou « pas sûr ».",
  plug4: "Un appel vocal ordinaire suffit : pas d'internet chez l'agriculteur, pas d'application, pas de lecture.",
  plug5: "Reste à faire : accord avec un opérateur, coût des minutes, vérification de l'appelant, consentement et règle de non-enregistrement.",
  realTitle: "Ce qui est réel, ce qui est simulé",
  real1: "Réel : le moteur d'irrigation (météo Open-Meteo), la voix de synthèse (ElevenLabs, voix Rima M), l'arbre de dialogue.",
  real2: "Simulé : le téléphone et le réseau téléphonique.",
  real3: "Arabe : arabe standard simple lu avec un accent tunisien, pas de dialecte garanti. Textes à valider par un Tunisien.",
  real4: "Le conseil est indicatif : une personne décide. À valider auprès de l'administration agricole régionale.",
  sizes: "Phrases fixes : {n} fichiers ({kb} Ko, deux langues). Une lecture de plan pèse environ {planKb} Ko.",
  talkLink: "Parler à l'agent vocal (extension)",
  hint_lang_fr: "Français",
  hint_lang_ar: "العربية (arabe)",
  hint_region_other: "Une autre région",
  hint_again_yes: "Écouter une autre culture",
  hint_again_no: "Terminer l'appel",
  hint_again_detail: "Détail de la semaine",
  hint_skip: "Toute touche : passer à la suite",
  group_cereales: "Céréales",
  group_legumes: "Légumes",
  group_arbres: "Arbres",
  group_autres: "Autres cultures",
  ago_1: "Aujourd'hui",
  ago_2: "Hier ou avant-hier",
  ago_3: "Il y a 3 à 5 jours",
  ago_4: "Il y a plus de 5 jours",
  ago_9: "Je ne sais pas (le plan sera « pas sûr »)",
  voiceFootnote: "Voix : {voice} (ElevenLabs), sous-titres anglais pour le jury.",
  hint_rain: "Signaler de la pluie",
  loadingRain: "Enregistrement du signalement…",
  rainTitle: "Signalement de pluie",
  rainSaved: "Enregistré : {level} à {region}, aujourd'hui.",
  rainCount: "{n} personne(s) différente(s) ont signalé aujourd'hui dans cette région.",
  rainCounted: "Pris en compte : la pluie du modèle météo est remplacée par la valeur prudente signalée pour ce jour (médiane des signalements).",
  rainNotYet: "Pas encore pris en compte : il faut au moins {min} personnes différentes qui signalent la même journée.",
  rainNotSaved: "Pas enregistré : le serveur n'a pas pu garder le signalement pour le moment. L'appel l'a dit.",
  rainNotSavedOffline: "Pas enregistré : un signalement a besoin d'internet pour être gardé. L'appel l'a dit.",
  rainDemoNote: "Dans la démonstration, les signalements sont fictifs. Ils sont « signalés par des agriculteurs » : ce n'est jamais une mesure. Aucun nom, aucun numéro, aucune adresse n'est gardé.",
};

const en: Dict = {
  title: "Voice line: call Sakia",
  langOrderTitle: "Why English first?",
  langOrder:
    "Subtitles come in English first, for the international jury. In reality the product speaks Tunisian Darija first, then French, then English only if useful: English is little spoken here. Today key 2 reads simple standard Arabic with a Tunisian accent; Darija is not yet recorded nor validated by a Tunisian speaker.",
  intro:
    "For the farmer who cannot read: they call, listen to the advice in a voice with a Tunisian accent, and choose with the keypad. A basic phone and a voice network are enough: no internet, no app, no reading.",
  stat:
    "In Kairouan, 25.5 to 28.5% of adults cannot read (INS 2024), and an SMS is useless to someone who cannot read. In the ICT2Scale pilot (ICARDA/GIZ), only 15% of farmers received the SMS at the right time: they asked for voice calls.",
  simulated: "SIMULATION: this phone is drawn. No real number, no real call, and your calls are not recorded.",
  callBtn: "Call Sakia",
  hangBtn: "Hang up",
  callAgain: "Call again",
  idleHint: "Press “Call Sakia”, then use the keypad (or your keyboard).",
  ringing: "Ringing…",
  active: "Call in progress",
  ended: "Call ended",
  duration: "Duration",
  maxCall: "The line ends by itself after 2 minutes.",
  speaking: "Sakia is speaking",
  listening: "Your turn: press a key",
  loadingPlan: "Working out the advice…",
  keysNow: "Keys available now (a helper for the simulation)",
  alwaysKeys: "0: repeat · *: go back",
  transcript: "Call transcript (it stays in this page, nothing is recorded)",
  youPressed: "You: key {k}",
  noHang: "Call hung up.",
  sourceTitle: "Where does the voice of the advice come from?",
  sourceAuto: "Automatic: live voice with today's weather; without internet, a demo recording",
  sourceRec: "Recordings only (simulates having no internet)",
  online: "Internet: yes",
  offline: "Internet: no",
  bannerLive: "Live voice · weather of {date}",
  bannerCache: "Voice already synthesised for this text (server memory) · weather of {date}",
  bannerRec: "DEMO RECORDING: replay of {date} (weather observed that day), not today's weather.",
  bannerNoVoiceBudget: "The live voice is paused (the demo budget is used up): the advice is shown on screen only.",
  bannerNoVoice: "The voice is not available right now: the advice is shown on screen only.",
  bannerNoRec: "No recording for this choice without internet. Recorded choices: {list}. The call therefore says “not sure: ask a technician”.",
  bannerError: "The advice could not be worked out. The call says “not sure: ask a technician”.",
  bannerRecChoices: "Offline, the recordings cover: {list}.",
  recList2: "key 2 (watered yesterday or the day before): {crops}",
  recList9: "key 9 (I do not know): {crops}",
  guardTitle: "Safeguard",
  guardNone: "No advice given: the weather data is too old. Ask an agricultural technician (CRDA).",
  guardAsk: "I am not sure: please ask an agricultural technician (CRDA).",
  guardOk: "The engine has no reservation about this advice (recent data, last irrigation known).",
  guardWaiting: "Shown after an advice is read. When the engine is not sure, the call says so out loud.",
  guardWhy: "Why:",
  reason_very_stale_data: "the weather data is more than 48 hours old",
  reason_stale_data: "the weather data is more than 12 hours old",
  reason_unknown_last_irrigation: "the last irrigation is not known",
  reason_analogy_coefficients: "this crop's coefficients are estimated by analogy",
  reason_uncertain_rain: "rain is possible within 3 days",
  reason_short_horizon: "the forecast does not cover the whole week",
  prepTitle: "Listen without internet",
  prepText:
    "Keeps the {n} recordings ({size}) in this browser: the menu sentences and the demo plans. After that the line works in airplane mode. The page itself must have been opened once with internet.",
  prepBtn: "Get ready for offline",
  prepRunning: "Downloading: {done} / {total}",
  prepDone: "Ready: {n} files kept in this browser.",
  prepPartial: "{n} of {total} files kept. Try again with internet.",
  plugTitle: "How it would plug in (not built)",
  plug1: "A short number from a Tunisian operator, or a SIP line from a telephony provider. No number exists today.",
  plug2: "Each key received is sent to POST /api/ivr/step: the same state machine as this fake phone. The answer lists the audio files to play.",
  plug3: "The advice read aloud comes from GET /api/ivr/plan-audio: same irrigation engine, same “not sure” safeguard.",
  plug4: "An ordinary voice call is enough: no internet for the farmer, no app, no reading.",
  plug5: "Still to do: an agreement with an operator, the cost of minutes, caller verification, consent and a no-recording rule.",
  realTitle: "What is real, what is simulated",
  real1: "Real: the irrigation engine (Open-Meteo weather), the synthetic voice (ElevenLabs, Rima M voice), the dialogue tree.",
  real2: "Simulated: the phone and the telephone network.",
  real3: "Arabic: simple Modern Standard Arabic read with a Tunisian accent, no dialect guaranteed. Texts to be validated by a Tunisian speaker.",
  real4: "The advice is indicative: a person decides. To be checked with the regional agriculture office.",
  sizes: "Fixed sentences: {n} files ({kb} KB, two languages). One plan reading weighs about {planKb} KB.",
  talkLink: "Talk to the voice agent (extension)",
  hint_lang_fr: "French",
  hint_lang_ar: "Arabic (العربية)",
  hint_region_other: "Another region",
  hint_again_yes: "Hear another crop",
  hint_again_no: "End the call",
  hint_again_detail: "Week details",
  hint_skip: "Any key: skip to the next step",
  group_cereales: "Cereals",
  group_legumes: "Vegetables",
  group_arbres: "Trees",
  group_autres: "Other crops",
  ago_1: "Today",
  ago_2: "Yesterday or the day before",
  ago_3: "3 to 5 days ago",
  ago_4: "More than 5 days ago",
  ago_9: "I do not know (the plan will say “not sure”)",
  voiceFootnote: "Voice: {voice} (ElevenLabs), English subtitles for the jury.",
  hint_rain: "Report rain",
  loadingRain: "Saving your report…",
  rainTitle: "Rain report",
  rainSaved: "Saved: {level} in {region}, today.",
  rainCount: "{n} different person(s) have reported today in this region.",
  rainCounted: "Taken into account: the rain of the weather model is replaced by the cautious value reported for this day (median of the reports).",
  rainNotYet: "Not taken into account yet: at least {min} different people must report the same day.",
  rainNotSaved: "Not saved: the server could not keep the report right now. The call said so.",
  rainNotSavedOffline: "Not saved: a report needs internet to be kept. The call said so.",
  rainDemoNote: "In this demo, reports are fictitious. They are “reported by farmers”, never a measurement. No name, number or address is kept.",
};

const ar: Dict = {
  title: "الخط الصوتي: اتصلوا بساقية",
  langOrderTitle: "لماذا الإنجليزية أولا؟",
  langOrder:
    "الترجمة تظهر بالإنجليزية أولا من أجل لجنة التحكيم الدولية. أما في الواقع فالمنتج يتكلم أولا بالدارجة التونسية ثم بالفرنسية ثم بالإنجليزية عند الحاجة، فالإنجليزية قليلة الاستعمال هنا. اليوم يقرأ الزر 2 عربية فصحى بسيطة بلكنة تونسية؛ والدارجة لم تُسجَّل بعد ولم يراجعها متحدث تونسي.",
  intro:
    "لمن لا يقرأ: يتصل الفلاح، فيسمع النصيحة بصوت بلكنة تونسية، ويختار بأزرار الهاتف. يكفي هاتف بسيط وشبكة صوتية: لا إنترنت ولا تطبيق ولا قراءة.",
  stat:
    "في القيروان، 25,5 إلى 28,5 % من الكبار لا يقرؤون (المعهد الوطني للإحصاء 2024)، والرسالة النصية لا تنفع من لا يقرأ. في المشروع التجريبي ICT2Scale لم يتلقَّ الرسائل في الوقت المناسب إلا 15 % من الفلاحين، وطلبوا مكالمات صوتية.",
  simulated: "محاكاة: هذا الهاتف مرسوم. لا رقم حقيقي ولا مكالمة حقيقية ولا تسجيل لمكالماتكم.",
  callBtn: "اتصل بساقية",
  hangBtn: "إنهاء المكالمة",
  callAgain: "اتصل من جديد",
  idleHint: "اضغطوا على «اتصل بساقية» ثم على أزرار الهاتف (أو لوحة المفاتيح).",
  ringing: "يرنّ الهاتف…",
  active: "المكالمة جارية",
  ended: "انتهت المكالمة",
  duration: "المدة",
  maxCall: "ينتهي الخط تلقائيا بعد دقيقتين.",
  speaking: "ساقية تتكلم",
  listening: "دوركم: اضغطوا زرا",
  loadingPlan: "جارٍ حساب النصيحة…",
  keysNow: "الأزرار الممكنة الآن (مساعدة للمحاكاة)",
  alwaysKeys: "0: للإعادة · *: للرجوع",
  transcript: "نص المكالمة (يبقى في هذه الصفحة، ولا يُسجَّل شيء)",
  youPressed: "أنتم: الزر {k}",
  noHang: "تم إنهاء المكالمة.",
  sourceTitle: "من أين يأتي صوت النصيحة؟",
  sourceAuto: "تلقائي: صوت مباشر بطقس اليوم؛ وبدون إنترنت، تسجيل تجريبي",
  sourceRec: "التسجيلات فقط (لمحاكاة غياب الإنترنت)",
  online: "الإنترنت: نعم",
  offline: "الإنترنت: لا",
  bannerLive: "صوت مباشر · طقس {date}",
  bannerCache: "صوت سبق توليده لهذا النص (ذاكرة الخادم) · طقس {date}",
  bannerRec: "تسجيل تجريبي: إعادة ليوم {date} (طقس مرصود في ذلك اليوم)، وليس طقس اليوم.",
  bannerNoVoiceBudget: "الصوت المباشر متوقف (نفدت ميزانية العرض): النصيحة معروضة على الشاشة فقط.",
  bannerNoVoice: "الصوت غير متوفر حاليا: النصيحة معروضة على الشاشة فقط.",
  bannerNoRec: "لا يوجد تسجيل لهذا الاختيار بدون إنترنت. الاختيارات المسجلة: {list}. لذلك تقول المكالمة «لست متأكدا: اسألوا فنيا».",
  bannerError: "تعذر حساب النصيحة. تقول المكالمة «لست متأكدا: اسألوا فنيا».",
  bannerRecChoices: "بدون إنترنت، تغطي التسجيلات: {list}.",
  recList2: "الزر 2 (سقيتم أمس أو أول أمس): {crops}",
  recList9: "الزر 9 (لا أعرف): {crops}",
  guardTitle: "صمام الأمان",
  guardNone: "لا نصيحة: بيانات الطقس قديمة جدا. اسألوا فنيا فلاحيا (CRDA).",
  guardAsk: "لست متأكدا: اسألوا فنيا فلاحيا (المندوبية الجهوية للتنمية الفلاحية).",
  guardOk: "لا تحفظ لدى المحرك على هذه النصيحة (بيانات حديثة، وآخر سقي معروف).",
  guardWaiting: "يظهر بعد قراءة نصيحة. حين لا يكون المحرك متأكدا، تقول المكالمة ذلك بصوت مسموع.",
  guardWhy: "السبب:",
  reason_very_stale_data: "بيانات الطقس أقدم من 48 ساعة",
  reason_stale_data: "بيانات الطقس أقدم من 12 ساعة",
  reason_unknown_last_irrigation: "تاريخ آخر سقي غير معروف",
  reason_analogy_coefficients: "معاملات هذا المحصول مقدرة بالمقارنة",
  reason_uncertain_rain: "قد تسقط أمطار خلال 3 أيام",
  reason_short_horizon: "التوقعات لا تغطي الأسبوع كله",
  prepTitle: "الاستماع بدون إنترنت",
  prepText:
    "يحفظ في هذا المتصفح {n} تسجيلا ({size}): جمل القائمة وخطط العرض التجريبية. بعدها يعمل الخط في وضع الطيران. يجب أن تكونوا فتحتم الصفحة مرة واحدة مع الإنترنت.",
  prepBtn: "التحضير للعمل بدون إنترنت",
  prepRunning: "جارٍ التحميل: {done} / {total}",
  prepDone: "جاهز: {n} ملفا محفوظا في هذا المتصفح.",
  prepPartial: "حُفظ {n} ملفا من {total}. أعيدوا المحاولة مع الإنترنت.",
  plugTitle: "كيف سيُربط بالهاتف (غير منجز)",
  plug1: "رقم قصير لدى مشغّل تونسي، أو خط SIP لدى مزوّد اتصالات. لا يوجد أي رقم اليوم.",
  plug2: "كل زر يُستقبل يُرسل إلى POST /api/ivr/step: هي نفس آلة الحالات لهذا الهاتف المرسوم. والجواب يعطي ملفات الصوت التي يجب تشغيلها.",
  plug3: "النصيحة المقروءة تأتي من GET /api/ivr/plan-audio: نفس محرك السقي، ونفس صمام «لست متأكدا».",
  plug4: "تكفي مكالمة صوتية عادية: لا إنترنت عند الفلاح ولا تطبيق ولا قراءة.",
  plug5: "المتبقي: اتفاق مع مشغّل، كلفة الدقائق، التحقق من المتصل، الموافقة، وقاعدة عدم التسجيل.",
  realTitle: "ما هو حقيقي وما هو محاكى",
  real1: "حقيقي: محرك السقي (طقس Open-Meteo)، الصوت الاصطناعي (ElevenLabs، صوت Rima M)، شجرة الحوار.",
  real2: "محاكى: الهاتف وشبكة الهاتف.",
  real3: "العربية: فصحى بسيطة بلكنة تونسية، دون ضمان لهجة. النصوص تحتاج إلى مراجعة من متحدث تونسي.",
  real4: "النصيحة إرشادية: القرار لشخص. يجب التحقق منها لدى المصالح الفلاحية الجهوية.",
  sizes: "الجمل الثابتة: {n} ملفا ({kb} ك.ب، لغتان). قراءة خطة واحدة تزن حوالي {planKb} ك.ب.",
  talkLink: "تحدثوا إلى الوكيل الصوتي (إضافة)",
  hint_lang_fr: "الفرنسية (Français)",
  hint_lang_ar: "العربية",
  hint_region_other: "ولاية أخرى",
  hint_again_yes: "الاستماع إلى محصول آخر",
  hint_again_no: "إنهاء المكالمة",
  hint_again_detail: "تفاصيل الأسبوع",
  hint_skip: "أي زر: للانتقال إلى التالي",
  group_cereales: "الحبوب",
  group_legumes: "الخضروات",
  group_arbres: "الأشجار",
  group_autres: "محاصيل أخرى",
  ago_1: "اليوم",
  ago_2: "أمس أو أول أمس",
  ago_3: "قبل 3 إلى 5 أيام",
  ago_4: "قبل أكثر من 5 أيام",
  ago_9: "لا أعرف (ستكون الخطة «غير متأكد»)",
  voiceFootnote: "الصوت: {voice} (ElevenLabs)، ترجمة إنجليزية للجنة التحكيم.",
  hint_rain: "التبليغ عن مطر",
  loadingRain: "جارٍ تسجيل التبليغ…",
  rainTitle: "تبليغ عن مطر",
  rainSaved: "تم التسجيل: {level} في {region}، اليوم.",
  rainCount: "بلّغ اليوم {n} أشخاص مختلفين في هذه الولاية.",
  rainCounted: "مأخوذ في الحساب: يحل المقدار الحذر المبلغ عنه لهذا اليوم (وسيط التبليغات) محل مطر نموذج الطقس.",
  rainNotYet: "لم يؤخذ في الحساب بعد: يلزم على الأقل {min} أشخاص مختلفين يبلغون عن اليوم نفسه.",
  rainNotSaved: "لم يُسجَّل: تعذر على الخادم حفظ التبليغ حاليا. قالت المكالمة ذلك.",
  rainNotSavedOffline: "لم يُسجَّل: يحتاج التبليغ إلى الإنترنت ليُحفظ. قالت المكالمة ذلك.",
  rainDemoNote: "في هذا العرض التبليغات وهمية. هي «تبليغات من فلاحين» وليست قياسا أبدا. لا يُحفظ أي اسم أو رقم أو عنوان.",
};

const DICTS: Record<UiLang, Dict> = { fr, en, ar };

export function tr(lang: UiLang, key: string, vars?: Record<string, string | number>): string {
  const raw = DICTS[lang][key] ?? DICTS.en[key] ?? key;
  return vars ? raw.replace(/\{(\w+)\}/g, (_, k) => String(vars[k] ?? `{${k}}`)) : raw;
}

export const LOCALES: Record<UiLang, string> = { fr: "fr-FR", en: "en-GB", ar: "ar-TN-u-nu-latn" };
